### ISSUE TITLE
Collaborate on a unified ldap library

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [ltb-project/ltb-ldap#1]
Hello @coudot 

as mentionned in https://github.com/ltb-project/white-pages/issues/119 maybe we can have one ldap library in common around all our php ldap projects

Cheers

**Comment by coudot** [comment]
Hello @bilbo-the-hobbit 

thanks for your message. Indeed collaboration is always a good thing. We do not have complex needs for the moment in LTB applications, we will try to start by the LDAP connection handling.
