### ISSUE TITLE
modify_attributes_using_ppolicy function does not compute correctly its return values

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/ltb-ldap#14]
Following variable values in modify_attributes_using_ppolicy  function have changed, causing regressions in self-service-password:

```
        $error_code = "";
        $error_msg = "";
        $matcheddn = null;
        $referrals = array();
        $ctrls = array();
```

We should restore default values:
```
        $error_code = null;
        $error_msg = null;
        $matcheddn = null;
        $referrals = null;
        $ctrls = null;
```

**Comment by davidcoutadeur** [comment]
This is due to `\Ltb\PhpLDAP::ldap_mod_replace_ext` not passing its arguments by reference

**Comment by davidcoutadeur** [comment]
TODO: 

- [ ] Need to write the corresponding test

**Comment by coudot** [comment]
Hello,

the fix is correctly working for me!
